class Numbers:

    def __init__(self, display, fg_color, bg_color=None):
        self._display = display
        self.fg_color = fg_color
        self.bg_color = bg_color
        self._all_height = 11
        self._all_width = 19

    def draw(self, number, x, y):
        str_number = str(number)
        clear_height = 0
        for i in str_number:
            clear_height += self._all_height
        if self.bg_color != None:
            self.bg_color.enable_color()
            self._display.rectangle(x, y-clear_height+1, self._all_width, clear_height)
        self.fg_color.enable_color()
        next_y = y
        for i in str_number:
            next_y = self._draw_number(i, x, next_y)

    def _draw_number(self, number, x, y):
        if number == "1":
            # Line 1
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            # Line 2
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            # Line 3
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-4)
            self._display.pixel(x+2, y-5)
            # Line 4
            self._display.pixel(x+3, y-3)
            self._display.pixel(x+3, y-4)
            self._display.pixel(x+3, y-5)
            # Line 5
            self._display.pixel(x+4, y-3)
            self._display.pixel(x+4, y-4)
            self._display.pixel(x+4, y-5)
            # Line 6
            self._display.pixel(x+5, y-3)
            self._display.pixel(x+5, y-4)
            self._display.pixel(x+5, y-5)
            # Line 7
            self._display.pixel(x+6, y-3)
            self._display.pixel(x+6, y-4)
            self._display.pixel(x+6, y-5)
            # Line 8
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            # Line 9
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            # Line 10
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            # Line 11
            self._display.pixel(x+10, y-3)
            self._display.pixel(x+10, y-4)
            self._display.pixel(x+10, y-5)
            # Line 12
            self._display.pixel(x+11, y-3)
            self._display.pixel(x+11, y-4)
            self._display.pixel(x+11, y-5)
            # Line 13
            self._display.pixel(x+12, y-3)
            self._display.pixel(x+12, y-4)
            self._display.pixel(x+12, y-5)
            # Line 14
            self._display.pixel(x+13, y-3)
            self._display.pixel(x+13, y-4)
            self._display.pixel(x+13, y-5)
            # Line 15
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-4)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            # Line 16
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y-1)
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            self._display.pixel(x+16, y-7)
            return y-11
        elif number == "2":
            # Line 1
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            # Line 2
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            self._display.pixel(x+7, y-8)
            # Line 9
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            self._display.pixel(x+8, y-7)
            self._display.pixel(x+8, y-8)
            # Line 10
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            # Line 11
            self._display.pixel(x+10, y-3)
            self._display.pixel(x+10, y-4)
            self._display.pixel(x+10, y-5)
            self._display.pixel(x+10, y-6)
            # Line 12
            self._display.pixel(x+11, y-2)
            self._display.pixel(x+11, y-3)
            self._display.pixel(x+11, y-4)
            self._display.pixel(x+11, y-5)
            # Line 13
            self._display.pixel(x+12, y-1)
            self._display.pixel(x+12, y-2)
            self._display.pixel(x+12, y-3)
            self._display.pixel(x+12, y-4)
            # Line 14
            self._display.pixel(x+13, y)
            self._display.pixel(x+13, y-1)
            self._display.pixel(x+13, y-2)
            self._display.pixel(x+13, y-3)
            # Line 15
            self._display.pixel(x+14, y)
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-4)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            self._display.pixel(x+15, y-8)
            # Line 17
            self._display.pixel(x+16, y)
            self._display.pixel(x+16, y-1)
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            self._display.pixel(x+16, y-7)
            self._display.pixel(x+16, y-8)
            return y-11
        elif number == "3":
            # Line 1
            self._display.pixel(x, y)
            self._display.pixel(x, y-1)
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            # Line 2
            self._display.pixel(x+1, y)
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y-5)
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y-5)
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            # Line 9
            self._display.pixel(x+8, y-1)
            self._display.pixel(x+8, y-2)
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            # Line 10
            self._display.pixel(x+9, y-1)
            self._display.pixel(x+9, y-2)
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            # Line 11
            self._display.pixel(x+10, y-5)
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y-5)
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+14, y)
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-4)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y)
            self._display.pixel(x+16, y-1)
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            return y-11
        elif number == "4":
            # Line 1
            self._display.pixel(x, y)
            self._display.pixel(x, y-1)
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-6)
            self._display.pixel(x, y-7)
            self._display.pixel(x, y-8)
            # Line 2
            self._display.pixel(x+1, y)
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            self._display.pixel(x+1, y-8)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y)
            self._display.pixel(x+4, y-1)
            self._display.pixel(x+4, y-2)
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y)
            self._display.pixel(x+5, y-1)
            self._display.pixel(x+5, y-2)
            self._display.pixel(x+5, y-3)
            self._display.pixel(x+5, y-4)
            self._display.pixel(x+5, y-5)
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y)
            self._display.pixel(x+6, y-1)
            self._display.pixel(x+6, y-2)
            self._display.pixel(x+6, y-3)
            self._display.pixel(x+6, y-4)
            self._display.pixel(x+6, y-5)
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y)
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            self._display.pixel(x+7, y-8)
            # Line 9
            self._display.pixel(x+8, y-6)
            self._display.pixel(x+8, y-7)
            self._display.pixel(x+8, y-8)
            # Line 10
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            self._display.pixel(x+9, y-8)
            # Line 11
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            self._display.pixel(x+15, y-8)
            # Line 17
            self._display.pixel(x+16, y-6)
            self._display.pixel(x+16, y-7)
            self._display.pixel(x+16, y-8)
            return y-11
        elif number == "5":
            # Line 1
            self._display.pixel(x, y)
            self._display.pixel(x, y-1)
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            self._display.pixel(x, y-7)
            self._display.pixel(x, y-8)
            # Line 2
            self._display.pixel(x+1, y)
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            self._display.pixel(x+1, y-8)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-4)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            # Line 5
            self._display.pixel(x+4, y)
            self._display.pixel(x+4, y-1)
            self._display.pixel(x+4, y-2)
            # Line 6
            self._display.pixel(x+5, y)
            self._display.pixel(x+5, y-1)
            self._display.pixel(x+5, y-2)
            # Line 7
            self._display.pixel(x+6, y)
            self._display.pixel(x+6, y-1)
            self._display.pixel(x+6, y-2)
            # Line 8
            self._display.pixel(x+7, y)
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            self._display.pixel(x+7, y-6)
            # Line 9
            self._display.pixel(x+8, y-1)
            self._display.pixel(x+8, y-2)
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            # Line 10
            self._display.pixel(x+9, y-1)
            self._display.pixel(x+9, y-2)
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            # Line 11
            self._display.pixel(x+10, y-5)
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y-5)
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            self._display.pixel(x+15, y-8)
            # Line 16
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y)
            self._display.pixel(x+16, y-1)
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            return y-11
        elif number == "6":
            # Line 1
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            self._display.pixel(x, y-7)
            # Line 2
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            self._display.pixel(x+1, y-8)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-4)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            self._display.pixel(x+3, y-3)
            # Line 5
            self._display.pixel(x+4, y)
            self._display.pixel(x+4, y-1)
            self._display.pixel(x+4, y-2)
            # Line 6
            self._display.pixel(x+5, y)
            self._display.pixel(x+5, y-1)
            self._display.pixel(x+5, y-2)
            # Line 7
            self._display.pixel(x+6, y)
            self._display.pixel(x+6, y-1)
            self._display.pixel(x+6, y-2)
            # Line 8
            self._display.pixel(x+7, y)
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            # Line 9
            self._display.pixel(x+8, y)
            self._display.pixel(x+8, y-1)
            self._display.pixel(x+8, y-2)
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            self._display.pixel(x+8, y-7)
            # Line 10
            self._display.pixel(x+9, y)
            self._display.pixel(x+9, y-1)
            self._display.pixel(x+9, y-2)
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            self._display.pixel(x+9, y-8)
            # Line 11
            self._display.pixel(x+10, y)
            self._display.pixel(x+10, y-1)
            self._display.pixel(x+10, y-2)
            self._display.pixel(x+10, y-3)
            self._display.pixel(x+10, y-5)
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y)
            self._display.pixel(x+11, y-1)
            self._display.pixel(x+11, y-2)
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y)
            self._display.pixel(x+12, y-1)
            self._display.pixel(x+12, y-2)
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y)
            self._display.pixel(x+13, y-1)
            self._display.pixel(x+13, y-2)
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+14, y)
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            return y-11
        elif number == "7":
            # Line 1
            self._display.pixel(x, y)
            self._display.pixel(x, y-1)
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            self._display.pixel(x, y-7)
            self._display.pixel(x, y-8)
            # Line 2
            self._display.pixel(x+1, y)
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            self._display.pixel(x+1, y-8)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-4)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y-5)
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            # Line 9
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            # Line 10
            self._display.pixel(x+9, y-2)
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            # Line 11
            self._display.pixel(x+10, y-2)
            self._display.pixel(x+10, y-3)
            self._display.pixel(x+10, y-4)
            # Line 12
            self._display.pixel(x+11, y-1)
            self._display.pixel(x+11, y-2)
            self._display.pixel(x+11, y-3)
            # Line 13
            self._display.pixel(x+12, y-1)
            self._display.pixel(x+12, y-2)
            self._display.pixel(x+12, y-3)
            # Line 14
            self._display.pixel(x+13, y)
            self._display.pixel(x+13, y-1)
            self._display.pixel(x+13, y-2)
            self._display.pixel(x+13, y-3)
            # Line 15
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            # Line 16
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            # Line 17
            self._display.pixel(x+16, y)
            self._display.pixel(x+16, y-1)
            self._display.pixel(x+16, y-2)
            return y-11
        elif number == "8":
            # Line 1
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            # Line 2
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y)
            self._display.pixel(x+4, y-1)
            self._display.pixel(x+4, y-2)
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y)
            self._display.pixel(x+5, y-1)
            self._display.pixel(x+5, y-2)
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y)
            self._display.pixel(x+6, y-1)
            self._display.pixel(x+6, y-2)
            self._display.pixel(x+6, y-3)
            self._display.pixel(x+6, y-5)
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            # Line 9
            self._display.pixel(x+8, y-2)
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            # Line 10
            self._display.pixel(x+9, y-1)
            self._display.pixel(x+9, y-2)
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            # Line 11
            self._display.pixel(x+10, y)
            self._display.pixel(x+10, y-1)
            self._display.pixel(x+10, y-2)
            self._display.pixel(x+10, y-3)
            self._display.pixel(x+10, y-5)
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y)
            self._display.pixel(x+11, y-1)
            self._display.pixel(x+11, y-2)
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y)
            self._display.pixel(x+12, y-1)
            self._display.pixel(x+12, y-2)
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y)
            self._display.pixel(x+13, y-1)
            self._display.pixel(x+13, y-2)
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+14, y)
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            return y-11
        elif number == "9":
            # Line 1
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            # Line 2
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y)
            self._display.pixel(x+4, y-1)
            self._display.pixel(x+4, y-2)
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y)
            self._display.pixel(x+5, y-1)
            self._display.pixel(x+5, y-2)
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y)
            self._display.pixel(x+6, y-1)
            self._display.pixel(x+6, y-2)
            self._display.pixel(x+6, y-3)
            self._display.pixel(x+6, y-5)
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y)
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-3)
            self._display.pixel(x+7, y-4)
            self._display.pixel(x+7, y-5)
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            self._display.pixel(x+7, y-8)
            # Line 9
            self._display.pixel(x+8, y-1)
            self._display.pixel(x+8, y-2)
            self._display.pixel(x+8, y-3)
            self._display.pixel(x+8, y-4)
            self._display.pixel(x+8, y-5)
            self._display.pixel(x+8, y-6)
            self._display.pixel(x+8, y-7)
            self._display.pixel(x+8, y-8)
            # Line 10
            self._display.pixel(x+9, y-3)
            self._display.pixel(x+9, y-4)
            self._display.pixel(x+9, y-5)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            self._display.pixel(x+9, y-8)
            # Line 11
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y-5)
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+14, y)
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-4)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y)
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y-1)
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            return y-11
        elif number == "0":
            # Line 1
            self._display.pixel(x, y-2)
            self._display.pixel(x, y-3)
            self._display.pixel(x, y-4)
            self._display.pixel(x, y-5)
            self._display.pixel(x, y-6)
            # Line 2
            self._display.pixel(x+1, y-1)
            self._display.pixel(x+1, y-2)
            self._display.pixel(x+1, y-3)
            self._display.pixel(x+1, y-4)
            self._display.pixel(x+1, y-5)
            self._display.pixel(x+1, y-6)
            self._display.pixel(x+1, y-7)
            # Line 3
            self._display.pixel(x+2, y)
            self._display.pixel(x+2, y-1)
            self._display.pixel(x+2, y-2)
            self._display.pixel(x+2, y-3)
            self._display.pixel(x+2, y-5)
            self._display.pixel(x+2, y-6)
            self._display.pixel(x+2, y-7)
            self._display.pixel(x+2, y-8)
            # Line 4
            self._display.pixel(x+3, y)
            self._display.pixel(x+3, y-1)
            self._display.pixel(x+3, y-2)
            self._display.pixel(x+3, y-6)
            self._display.pixel(x+3, y-7)
            self._display.pixel(x+3, y-8)
            # Line 5
            self._display.pixel(x+4, y)
            self._display.pixel(x+4, y-1)
            self._display.pixel(x+4, y-2)
            self._display.pixel(x+4, y-6)
            self._display.pixel(x+4, y-7)
            self._display.pixel(x+4, y-8)
            # Line 6
            self._display.pixel(x+5, y)
            self._display.pixel(x+5, y-1)
            self._display.pixel(x+5, y-2)
            self._display.pixel(x+5, y-6)
            self._display.pixel(x+5, y-7)
            self._display.pixel(x+5, y-8)
            # Line 7
            self._display.pixel(x+6, y)
            self._display.pixel(x+6, y-1)
            self._display.pixel(x+6, y-2)
            self._display.pixel(x+6, y-6)
            self._display.pixel(x+6, y-7)
            self._display.pixel(x+6, y-8)
            # Line 8
            self._display.pixel(x+7, y)
            self._display.pixel(x+7, y-1)
            self._display.pixel(x+7, y-2)
            self._display.pixel(x+7, y-6)
            self._display.pixel(x+7, y-7)
            self._display.pixel(x+7, y-8)
            # Line 9
            self._display.pixel(x+8, y)
            self._display.pixel(x+8, y-1)
            self._display.pixel(x+8, y-2)
            self._display.pixel(x+8, y-6)
            self._display.pixel(x+8, y-7)
            self._display.pixel(x+8, y-8)
            # Line 10
            self._display.pixel(x+9, y)
            self._display.pixel(x+9, y-1)
            self._display.pixel(x+9, y-2)
            self._display.pixel(x+9, y-6)
            self._display.pixel(x+9, y-7)
            self._display.pixel(x+9, y-8)
            # Line 11
            self._display.pixel(x+10, y)
            self._display.pixel(x+10, y-1)
            self._display.pixel(x+10, y-2)
            self._display.pixel(x+10, y-6)
            self._display.pixel(x+10, y-7)
            self._display.pixel(x+10, y-8)
            # Line 12
            self._display.pixel(x+11, y)
            self._display.pixel(x+11, y-1)
            self._display.pixel(x+11, y-2)
            self._display.pixel(x+11, y-6)
            self._display.pixel(x+11, y-7)
            self._display.pixel(x+11, y-8)
            # Line 13
            self._display.pixel(x+12, y)
            self._display.pixel(x+12, y-1)
            self._display.pixel(x+12, y-2)
            self._display.pixel(x+12, y-6)
            self._display.pixel(x+12, y-7)
            self._display.pixel(x+12, y-8)
            # Line 14
            self._display.pixel(x+13, y)
            self._display.pixel(x+13, y-1)
            self._display.pixel(x+13, y-2)
            self._display.pixel(x+13, y-6)
            self._display.pixel(x+13, y-7)
            self._display.pixel(x+13, y-8)
            # Line 15
            self._display.pixel(x+14, y)
            self._display.pixel(x+14, y-1)
            self._display.pixel(x+14, y-2)
            self._display.pixel(x+14, y-3)
            self._display.pixel(x+14, y-5)
            self._display.pixel(x+14, y-6)
            self._display.pixel(x+14, y-7)
            self._display.pixel(x+14, y-8)
            # Line 16
            self._display.pixel(x+15, y-1)
            self._display.pixel(x+15, y-2)
            self._display.pixel(x+15, y-3)
            self._display.pixel(x+15, y-4)
            self._display.pixel(x+15, y-5)
            self._display.pixel(x+15, y-6)
            self._display.pixel(x+15, y-7)
            # Line 17
            self._display.pixel(x+16, y-2)
            self._display.pixel(x+16, y-3)
            self._display.pixel(x+16, y-4)
            self._display.pixel(x+16, y-5)
            self._display.pixel(x+16, y-6)
            return y-11
        else:
            return y-3
